### GET hello
GET http://localhost:8888/hello

### GET gw 1
GET http://localhost:8888/gw

### GET ga
GET http://localhost:8888/ga/aaa

### GET ga 1
POST http://localhost:8888/ga/cn.lokn.knrpc.demo.api.UserService
Content-Type:application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100],
  "methodSign": "findById@1_int"
}

### POST ga 2
POST http://localhost:8888/gw/kkrpc/cn.lokn.knrpc.demo.api.UserService
Content-Type:application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100],
  "methodSign": "findById@1_int"
}

### POST dirct
POST http://localhost:8888/gw/direct/cn.lokn.knrpc.demo.api.UserService
Content-Type:application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100],
  "methodSign": "findById@1_int"
}

### POST dirct backend
POST http://localhost:8888/gw/direct/cn.lokn.knrpc.demo.api.UserService?backend=http://localhost:8081/knrpc
Content-Type:application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100],
  "methodSign": "findById@1_int"
}